

const outletBalanceCode = {
    VENTALA_OUTLET_BALANCE: 100
}

const philhealthCode = {
    VALIDATE_CONTRIBUTION: 106,
    PROCESS_CONTRIBUTION: 106,
    TRANSACTION_INQUIRY: 107,
    CANCEL_TRANSACTION: 107,
}

const sssPaymentCode = {
    VALIDATE_CONTRIBUTION_SEARCH_BY_MEMBER: 152,
    PROCESS_CONTRIBUTION_SEARCH_BY_MEMBER: 152,
    VALIDATE_CONTRIBUTION_SEARCH_BY_PRN: 153,
    PROCESS_CONTRIBUTION_SEARCH_BY_PRN: 153,
    VALIDATE_CONTRIBUTION_CREATE_AND_PAY_PRN: 113,
    PROCESS_CONTRIBUTION_CREATE_AND_PAY_PRN: 113,
    VALIDATE_CONTRIBUTION_PAY_FOR_PRN: 154,
    PROCESS_CONTRIBUTION_PAY_FOR_PRN: 154,
    SEARCH_BY_RTPL_PRN: 158,
    PAY_FOR_RTPL_PRN: 159,
    REAL_ESTATE_LOAN_PAYMENT: 115,
    MISCELLANEOUS_PAYMENT: 116,
    INQUIRY_CONTRIBUTION_TRANSACTION: 113,
    INQUIRY_SHORT_TERM_LOAN_TRANSACTION: 114,
    INQUIRY_REAL_ESTATE_LOAN_TRANSACTION: 115,
    INQUIRY_MISCELLANEOUS_TRANSACTION: 116,
    CANCEL_REAL_ESTATE_LOAN_TRANSACTION: 115,
    CANCEL_MISCELLANEOUS_TRANSACTION: 116,

}

module.exports = {
    ...outletBalanceCode,
    ...philhealthCode,
    ...sssPaymentCode
}