
const VENATJA_IBG_CODES = {
    IBGPAYMENT: 109,
    IBGMPAYMENT: 110,
    STLOAN: 111,
    HLOAN: 112,
    IBG_PAYMENT_INQUIRY: 109,
    MODIFIED_IBG_PAYMENT_INQUIRY: 110,
    SHORT_TERM_LOAN_INQUIRY: 111,
    HOUSING_LOAN_INQUIRY: 112,
    CANCEL_IBG_PAYMENT: 109,
    CANCEL_MODIFIED_IBG_PAYMENT: 110,
    CANCEL_SHORT_TERM_LOAN: 111,
    CANCEL_HOUSING_LOAN: 112,
    CANCEL_TRANSACTION: 107,
    TRANSACTION_ENQUIRY: 107,
}

module.exports = {
    VENATJA_IBG_CODES
}